#!/usr/bin/env bash
# gpu-detect.sh — Auto-detects GPU bandwidth and generates optimized Ollama configuration.
#
# Uses NVIDIA NVML (libnvidia-ml.so.1) via Python ctypes — does NOT require nvidia-smi.
# NVML is injected by the NVIDIA container runtime (docker --gpus / count: all).
#
# Outputs $OUTPUT_FILE (default: /tmp/ollama-gpu-config.env) with:
#   CUDA_VISIBLE_DEVICES        — GPUs ordered worst-bandwidth-first, best-last.
#   OLLAMA_GPU_TIER_THRESHOLD   — CUDA index count of "legacy" GPUs (CC < 70).
#   OLLAMA_FLASH_ATTENTION      — 0 when legacy GPUs present (they lack tensor cores).
#   OLLAMA_KV_CACHE_TYPE        — f16 when legacy GPUs present (q4_0/q8_0 require FA).
#
# Portability: works on any NVIDIA GPU combination. Re-run after hardware changes.
# Disable: set OLLAMA_GPU_AUTODETECT=0.

OUTPUT_FILE="${1:-/tmp/ollama-gpu-config.env}"

python3 - "$OUTPUT_FILE" << 'PYEOF'
import sys
import ctypes

output_file = sys.argv[1]

# ── Load NVML ────────────────────────────────────────────────────────────────

NVML_PATHS = [
    "libnvidia-ml.so.1",
    "/usr/local/nvidia/lib64/libnvidia-ml.so.1",
    "/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1",
    "/usr/lib/libnvidia-ml.so.1",
]

nvml = None
for path in NVML_PATHS:
    try:
        nvml = ctypes.CDLL(path)
        break
    except OSError:
        continue

if nvml is None:
    with open(output_file, 'w') as f:
        f.write("# gpu-detect.sh: NVML (libnvidia-ml.so.1) not found\n")
        f.write("# Ensure container is started with --gpus or count: all\n")
    print("gpu-detect: NVML not found — no GPU config generated", file=sys.stderr)
    sys.exit(0)

try:
    ret = nvml.nvmlInit_v2()
    if ret != 0:
        nvml.nvmlInit()
except Exception:
    nvml.nvmlInit()

# ── Query GPUs ───────────────────────────────────────────────────────────────

count = ctypes.c_uint()
nvml.nvmlDeviceGetCount_v2(ctypes.byref(count))

NVML_CLOCK_MEM = 2  # nvmlClockType_t: NVML_CLOCK_MEM

class nvmlPciInfo_t(ctypes.Structure):
    _fields_ = [
        ('busIdLegacy', ctypes.c_char * 16),
        ('domain', ctypes.c_uint),
        ('bus', ctypes.c_uint),
        ('device', ctypes.c_uint),
        ('pciDeviceId', ctypes.c_uint),
        ('pciSubSystemId', ctypes.c_uint),
        ('busId', ctypes.c_char * 32),
    ]

gpus = []
for i in range(count.value):
    handle = ctypes.c_void_p()
    nvml.nvmlDeviceGetHandleByIndex_v2(i, ctypes.byref(handle))

    # UUID
    uuid_buf = ctypes.create_string_buffer(96)
    nvml.nvmlDeviceGetUUID(handle, uuid_buf, 96)
    uuid = uuid_buf.value.decode().strip()

    # Name
    name_buf = ctypes.create_string_buffer(96)
    nvml.nvmlDeviceGetName(handle, name_buf, 96)
    name = name_buf.value.decode().strip()

    # Compute capability
    major = ctypes.c_int()
    minor = ctypes.c_int()
    nvml.nvmlDeviceGetCudaComputeCapability(handle, ctypes.byref(major), ctypes.byref(minor))
    cc = major.value * 10 + minor.value

    # Memory bus width (bits)
    bus_width = ctypes.c_uint()
    try:
        nvml.nvmlDeviceGetMemoryBusWidth(handle, ctypes.byref(bus_width))
        bw_bits = bus_width.value
    except Exception:
        bw_bits = 128  # fallback

    # Max memory clock (MHz)
    mem_clock = ctypes.c_uint()
    try:
        nvml.nvmlDeviceGetMaxClockInfo(handle, NVML_CLOCK_MEM, ctypes.byref(mem_clock))
        mhz = mem_clock.value
    except Exception:
        mhz = 1000  # fallback

    # Bandwidth in GB/s: 2 × (bits/8) × MHz / 1000
    bw_gbs = int(2 * (bw_bits / 8) * mhz / 1000)

    gpus.append({
        'idx': i,
        'uuid': uuid,
        'name': name,
        'cc': cc,
        'bw_gbs': bw_gbs,
    })

nvml.nvmlShutdown()

if not gpus:
    with open(output_file, 'w') as f:
        f.write("# gpu-detect.sh: no GPUs found via NVML\n")
    sys.exit(0)

# ── Sort worst-bandwidth-first ────────────────────────────────────────────────
# Worst → lowest CUDA index → filled LAST by back-to-front algorithm.
# Best  → highest CUDA index → filled FIRST.

gpus.sort(key=lambda g: (g['bw_gbs'], g['cc']))

cuda_visible = ','.join(g['uuid'] for g in gpus)

# Legacy = CC < 70 (Kepler 37, Maxwell 50/52, Pascal 60/61)
# Fast   = CC >= 70 (Volta 70, Turing 75, Ampere 80/86, Ada 89, Hopper 90)
LEGACY_CC_MAX = 69
legacy_count = sum(1 for g in gpus if g['cc'] <= LEGACY_CC_MAX)

# Flash Attention: disable when any legacy GPU visible (they lack tensor cores).
# With tier patch, fast GPUs get all layers for small models, but Ollama's
# FA check sees ALL visible GPUs — pool-aware FA needs a Go patch (see roadmap).
has_legacy = legacy_count > 0
fa_enabled = 0 if has_legacy else 1
kv_cache_type = "f16" if has_legacy else "q4_0"

# GPU overhead: 256 MB per GPU
gpu_overhead = 268435456

# ── Write output ─────────────────────────────────────────────────────────────

lines = [
    "# Auto-generated by gpu-detect.sh via NVML — do not edit manually",
    f"# {len(gpus)} GPUs detected: {len(gpus)-legacy_count} fast (CC>={LEGACY_CC_MAX+1}), {legacy_count} legacy (CC<={LEGACY_CC_MAX})",
    "#",
    "# CUDA device ordering (worst bandwidth → lowest CUDA index, best → highest):",
]
for i, g in enumerate(gpus):
    tier = "LEGACY" if g['cc'] <= LEGACY_CC_MAX else "FAST  "
    lines.append(f"#   CUDA{i:2d}: [{tier}] {g['name']:28s}  CC={g['cc']:2d}  ~{g['bw_gbs']:4d} GB/s")

lines += [
    "#",
    f"# Tier threshold: CUDA 0..{max(legacy_count-1,0)} = legacy (overflow only)",
    f"#                 CUDA {legacy_count}..{len(gpus)-1} = fast (filled first)",
    "#",
    "# Flash Attention: NOT set here — handled by the patched LlamaServerFlashAttention()",
    "# in llm/llama_server.go (patch-ollama-fa.py). The patch enables FA automatically",
    "# when all GPUs that actually receive model layers support FA (CC >= 7.0).",
    "# Setting OLLAMA_FLASH_ATTENTION here would override the patch (Ollama treats it",
    "# as a user override and skips the tier-aware FA check).",
    "",
    f"CUDA_VISIBLE_DEVICES={cuda_visible}",
    f"OLLAMA_GPU_TIER_THRESHOLD={legacy_count}",
    f"OLLAMA_GPU_OVERHEAD={gpu_overhead}",
    "# KV cache type: f16 is safe with any FA setting. When FA is enabled by the patch,",
    "# changing to q4_0 reduces KV VRAM by 4x. Set OLLAMA_KV_CACHE_TYPE=q4_0 in",
    "# .env.multigpu once the FA patch is verified working on your hardware.",
]

with open(output_file, 'w') as f:
    f.write('\n'.join(lines) + '\n')

fast_names = [g['name'] for g in gpus if g['cc'] > LEGACY_CC_MAX]
legacy_names = [g['name'] for g in gpus if g['cc'] <= LEGACY_CC_MAX]
print(f"gpu-detect: {len(gpus)} GPUs | threshold={legacy_count} | FA={fa_enabled} | KV={kv_cache_type}")
if fast_names:
    print(f"  Fast:   {', '.join(dict.fromkeys(fast_names))}")
if legacy_names:
    print(f"  Legacy: {', '.join(dict.fromkeys(legacy_names))}")
PYEOF
